# Numpy basics

NumPy (Numerical Python) is an open-source Python library that's used in almost every field of science and engineering. It's the universal standard for working with numerical data in Python, and it's at the core of the scientific ecosystem in Python. NumPy provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Here are some of the basics of NumPy that are essential to understand:

## Installation
If you don't have NumPy installed, you can install it using pip:

In [1]:
# !pip install numpy

## Importing NumPy
To use NumPy, you first need to import it:

In [2]:
import numpy as np

## Creating NumPy Arrays
The primary data structure in NumPy is the ndarray, which stands for N-dimensional array.

### From a Python List

In [3]:
a = np.array([1, 2, 3])
print(a)  # Output: [1 2 3]

[1 2 3]


### Array of Zeros or Ones

In [4]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))

### Range and Reshape

In [5]:
range_array = np.arange(10)  # Array of 0 to 9
reshaped_array = np.arange(10).reshape(2, 5)  # 2x5 array with numbers 0 to 9

## Array Operations
NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data.

### Element-wise Operations

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print(a + b)  # Output: [5 7 9]

# Subtraction
print(a - b)  # Output: [-3 -3 -3]

# Multiplication
print(a * b)  # Output: [4 10 18]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


### Matrix Operations

In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Matrix Multiplication
product = np.dot(a, b)

## Indexing, Slicing, and Iterating
NumPy offers many ways to index into arrays.

### Indexing

In [8]:
a = np.array([1, 2, 3])
print(a[0])  # Output: 1

1


### Slicing

In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[1:5])  # Output: [2 3 4 5]

[2 3 4 5]


### Iterating

In [10]:
a = np.array([1, 2, 3])
for x in a:
    print(x)

1
2
3


## Statistical Methods
NumPy offers common statistical methods like mean, median, standard deviation, etc.

In [11]:
a = np.array([1, 2, 3, 4, 5])

# Mean
print(np.mean(a))

# Median
print(np.median(a))

# Standard Deviation
print(np.std(a))

3.0
3.0
1.4142135623730951


NumPy is a powerful library with many more functionalities. These basics are just the tip of the iceberg, but they are fundamental for anyone looking to work with numerical data in Python. As you get more comfortable with these basics, you can explore more advanced features of NumPy, such as broadcasting, advanced indexing, and more.